name: /home/daniel/anaconda-workspace/sample-ml-clustering/env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - rpds-py=0.29.0
  - libgcc-ng=15.2.0
  - statsmodels=0.14.5
  - libclang13=14.0.6=default_he11475f_1
  - psutil=7.1.3
  - jupyter_core=5.9.1
  - ply=3.11
  - brotli-python=1.2.0
  - libpq=12.17=hdbd6064_0
  - lz4-c=1.10.0
  - bleach=6.3.0
  - yaml=0.2.5
  - numpy-base=2.3.4
  - markupsafe=3.0.3
  - mkl-service=2.5.2
  - brotli=1.2.0
  - xz=5.8.1
  - notebook-shim=0.2.4
  - packaging=25.0
  - openpyxl=3.1.5
  - python-json-logger=2.0.7=py312h06a4308_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - libffi=3.5.2
  - tinycss2=1.5.0
  - icu=73.2
  - ca-certificates=2025.11.12
  - intel-openmp=2025.0.0
  - bottleneck=1.6.0
  - libdeflate=1.22
  - pyyaml=6.0.3
  - jupyterlab_server=2.28.0
  - decorator=5.2.1
  - glib=2.86.2
  - ipython=9.7.0
  - debugpy=1.8.17
  - rfc3339-validator=0.1.4
  - typing-extensions=4.15.0
  - libglib=2.86.2
  - libgfortran5=15.2.0
  - libxcb=1.17.0
  - parso=0.8.5
  - numpy=2.3.4
  - pyzmq=27.1.0
  - prometheus_client=0.23.1
  - jupyter_server=2.17.0
  - pyparsing=3.2.5
  - jinja2=3.1.6
  - libedit=3.1.20250104
  - bzip2=1.0.8
  - mkl_random=1.2.11
  - urllib3=2.5.0
  - jsonschema-specifications=2025.9.1
  - ncurses=6.5
  - glib-tools=2.86.2
  - wheel=0.45.1
  - libgfortran-ng=15.2.0
  - openjpeg=2.5.0
  - libxkbcommon=1.7.0
  - lcms2=2.15
  - libbrotlicommon=1.2.0
  - libxml2=2.12.7
  - typing_extensions=4.15.0
  - contourpy=1.3.3
  - unicodedata2=17.0.0
  - jedi=0.19.2
  - pycparser=2.22
  - websocket-client=1.9.0
  - ipykernel=7.1.0
  - libstdcxx-ng=15.2.0
  - wcwidth=0.2.14
  - mysql=5.7.24=h721c034_2
  - nbformat=5.10.4
  - pandas=2.3.3
  - jupyter_server_terminals=0.5.3
  - threadpoolctl=3.6.0
  - mkl_fft=2.0.0
  - comm=0.2.3
  - patsy=1.0.2
  - argon2-cffi=25.1.0
  - cycler=0.12.1
  - brotli-bin=1.2.0
  - argon2-cffi-bindings=25.1.0
  - requests=2.32.5
  - libclang=14.0.6=default_hc6dbbc7_1
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - freetype=2.14.1
  - zeromq=4.3.5
  - blas=2.302
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3=py312h06a4308_1
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - terminado=0.18.1
  - libllvm14=14.0.6
  - libuuid=2.41.2
  - jupyterlab=4.5.0
  - pcre2=10.47
  - dbus=1.16.2
  - pillow=11.0.0
  - asttokens=3.0.1
  - libbrotlidec=1.2.0
  - python-tzdata=2025.2
  - qtpy=2.4.3
  - tabulate=0.9.0
  - traitlets=5.14.3
  - widgetsnbextension=4.0.15
  - matplotlib-inline=0.2.1
  - python=3.12.12
  - readline=8.2
  - expat=2.7.3
  - openssl=3.6.0
  - nbclient=0.10.2
  - overrides=7.7.0
  - jupyter-lsp=2.3.0
  - xarray=2025.11.0
  - beautifulsoup4=4.14.2
  - pyqt5-sip=12.13.0
  - charset-normalizer=3.4.4
  - pybind11-abi=11
  - jsonschema=4.25.1
  - executing=2.2.1
  - notebook=7.5.0
  - qtconsole=5.7.0
  - cffi=2.0.0
  - _libgcc_mutex=0.1=conda_forge
  - soupsieve=2.8
  - anyio=4.11.0
  - async-lru=2.0.5
  - seaborn=0.13.2
  - pytz=2025.2
  - libwebp-base=1.6.0
  - tbb=2021.13.0
  - fonttools=4.60.1
  - mpmath=1.3.0
  - scipy=1.16.3
  - stack_data=0.6.3
  - prompt-toolkit=3.0.52
  - plotly=6.5.0
  - pip=25.3
  - jupyter_events=0.12.0
  - gstreamer=1.14.1=h5eee18b_1
  - qt-main=5.15.2=h53bd1ea_10
  - joblib=1.5.2
  - pyqt=5.15.10
  - mistune=3.1.4
  - send2trash=1.8.3
  - jpeg=9e
  - libgomp=15.2.0
  - sip=6.7.12=py312h6a678d5_0
  - webencodings=0.5.1
  - setuptools=80.9.0
  - sqlite=3.51.0
  - matplotlib-base=3.9.1
  - zstd=1.5.7
  - ld_impl_linux-64=2.45
  - ipywidgets=8.1.8
  - outdated=0.2.2
  - libpng=1.6.51
  - numexpr=2.14.1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pygments=2.19.2
  - et_xmlfile=2.0.0
  - pandas-flavor=0.7.0
  - libsodium=1.0.18
  - tenacity=9.1.2
  - pexpect=4.9.0
  - zlib=1.3.1
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - kiwisolver=1.4.9
  - matplotlib=3.9.1
  - pure_eval=0.2.3
  - littleutils=0.2.4
  - mkl=2024.2.2
  - fontconfig=2.15.0
  - six=1.17.0
  - libiconv=1.18
  - sniffio=1.3.1
  - nest-asyncio=1.6.0
  - libcups=2.4.2=h2d74bed_1
  - pysocks=1.7.1
  - tk=8.6.14=h39e8969_0
  - _openmp_mutex=4.5
  - idna=3.11
  - attrs=25.4.0
  - lerc=4.0.0
  - prompt_toolkit=3.0.52
  - krb5=1.20.1=h143b758_1
  - platformdirs=4.5.0
  - nbconvert=7.16.6
  - libtiff=4.5.1
  - jupyterlab_widgets=3.0.16
  - gst-plugins-base=1.14.1=h6a678d5_1
  - jupyterlab_pygments=0.3.0
  - python-fastjsonschema=2.21.2
  - tornado=6.5.2
  - referencing=0.37.0
  - tzdata=2025b
  - json5=0.12.1
  - certifi=2025.11.12
  - babel=2.17.0
  - pingouin=0.5.5
  - libbrotlienc=1.2.0
  - scikit-learn=1.7.2
  - jupyter=1.1.1
prefix: /home/daniel/anaconda-workspace/sample-ml-clustering/env
